sudo: required
before_install:
  - sudo apt-get install python3.5
  - sudo curl https://raw.githubusercontent.com/SivilTaram/TAScripts/master/CIScripts/python/check.py > check.py
script:
  - dir=$(ls -l | grep ^d | awk '/^d/ {print i$NF}' i=`pwd`'/')
  - for i in $dir;do mes=`python3 check.py $i`; if [ -n "$mes" ] ; then echo $i $mes; exit 66; fi; done
after_failure:
