sudo: required
before_install:
  - sudo apt-get install python3.5
  - sudo apt-get install jq
  - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
  - sudo chmod +x jq-linux64
  - sudo mv jq-linux64 $(which jq)
  - sudo curl https://raw.githubusercontent.com/SivilTaram/TAScripts/master/CIScripts/python/check.py > check.py
before_script:
  - sudo chmod ugo+x ./py-run.sh
script:
  - ./py-run.sh
