sudo: required
before_install:
  - sudo apt-get install python3.5
  - sudo apt-get install jq=1.5
  - sudo curl https://raw.githubusercontent.com/SivilTaram/TAScripts/master/CIScripts/python/check.py > check.py
before_script:
  - sudo chmod ugo+x ./py-run.sh
script:
  - ./py-run.sh
